"use client";

import { useState, useCallback } from "react";
import { useForm, type SubmitHandler } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { AlertCircle, CheckCircle2, Cloud, Loader2, Trash2, Shield } from "lucide-react";
import { createPropertySchema, CreatePropertyInput } from "@/src/lib/validations/property";
import { createProperty } from "@/src/lib/api/property";
import { apiClient } from "@/src/lib/api/client";
import { getErrorMessage } from "@/src/lib/api/errors";
import { Button } from "@/src/components/ui/Button";

interface PropertyFormProps {
  onClose?: () => void;
}

// Extend form input types locally if tier isn't natively in CreatePropertyInput yet
interface ExtendedPropertyInput extends CreatePropertyInput {
  tier: "premium" | "standard";
}

const PAYMENT_TIERS = [
  { id: "premium", name: "Premium Listing", duration: "30 Days", feature: "Featured Placement", price: 500 },
  { id: "standard", name: "Standard Listing", duration: "15 Days", feature: "Regular Search", price: 250 },
];

export function PropertyCreationForm({ onClose }: PropertyFormProps) {
  const [currentStep, setCurrentStep] = useState(1);
  const [uploadedImages, setUploadedImages] = useState<File[]>([]);
  const [previewUrls, setPreviewUrls] = useState<string[]>([]);
  const [uploadError, setUploadError] = useState<string>("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string>("");
  const [successMessage, setSuccessMessage] = useState<string>("");

  const {
    register,
    handleSubmit,
    formState: { errors },
    watch,
    setValue,
    getValues,
    trigger,
  } = useForm<ExtendedPropertyInput>({
    resolver: zodResolver(createPropertySchema) as any,
    mode: "onBlur",
    defaultValues: {
      category: "RESIDENTIAL",
      listing_type: "FOR_SALE",
      images: [],
      tier: "premium", // Default selection
    },
  });

  const watchListingType = watch("listing_type");
  const watchTier = watch("tier");
  const selectedTierData = PAYMENT_TIERS.find((t) => t.id === watchTier) || PAYMENT_TIERS[0];

  const handleImageSelect = useCallback(
    (files: FileList | null) => {
      if (!files) return;
      setUploadError("");
      const newFiles = Array.from(files);
      const totalFiles = uploadedImages.length + newFiles.length;

      if (totalFiles > 10) {
        setUploadError("Maximum 10 images allowed");
        return;
      }

      for (const file of newFiles) {
        if (!["image/jpeg", "image/png", "image/webp"].includes(file.type)) {
          setUploadError("Only JPG, PNG, and WebP files are allowed");
          return;
        }
        if (file.size > 5 * 1024 * 1024) {
          setUploadError("Each image must be less than 5MB");
          return;
        }
      }

      const newPreviews = newFiles.map((file) => URL.createObjectURL(file));
      setUploadedImages((prev) => {
        const nextImages = [...prev, ...newFiles];
        setValue("images", nextImages);
        return nextImages;
      });
      setPreviewUrls((prev) => [...prev, ...newPreviews]);
    },
    [uploadedImages, setValue]
  );

  const handleRemoveImage = (index: number) => {
    setUploadedImages((prev) => {
      const nextImages = prev.filter((_, i) => i !== index);
      setValue("images", nextImages);
      return nextImages;
    });
    setPreviewUrls((prev) => {
      URL.revokeObjectURL(prev[index]);
      return prev.filter((_, i) => i !== index);
    });
  };

  const validateStep = async () => {
    if (currentStep === 1) {
      return await trigger(["title", "category", "listing_type", "price", "address"]);
    }
    return true;
  };

  const handleNextStep = async () => {
    if (await validateStep()) setCurrentStep((prev) => prev + 1);
  };

  const handlePrevStep = () => setCurrentStep((prev) => Math.max(1, prev - 1));

  const onSubmit: SubmitHandler<ExtendedPropertyInput> = async (data) => {
    try {
      setIsSubmitting(true);
      setSubmitError("");
      setSuccessMessage("");

      const { tier, ...propertyPayload } = data;


      const cleanPrice = typeof propertyPayload.price === "string"
        ? (propertyPayload.price as string).replace(/,/g, "")
        : String(propertyPayload.price);

      const propertyResponse = await createProperty({
        ...propertyPayload,
        price: cleanPrice,
        images: uploadedImages,
      });

      setSuccessMessage("Property logged! Forwarding to safe payment interface...");

      const paymentResponse = await apiClient.post(
        `/payments/properties/${propertyResponse.property_id}/pay`,
      );

      if (onClose) onClose();

      if (paymentResponse.data?.checkout_url) {
        window.location.href = paymentResponse.data.checkout_url;
      } else {
        throw new Error("No secure checkout session URL was generated by the payment adapter.");
      }
    } catch (error: any) {
      console.error("Submission Failure Debug Log:", error.response?.data || error);

      const backendMessage = error.response?.data
        ? typeof error.response.data === "object"
          ? JSON.stringify(error.response.data)
          : error.response.data
        : "Failed to process form parameters.";

      setSubmitError(getErrorMessage(error, backendMessage));
      setIsSubmitting(false);
    }
  };

  const handleSaveDraftManual = async () => {
    const fieldsAreValid = await trigger(["title", "category"]);
    if (!fieldsAreValid) {
      setSubmitError("Please fill out at least Title and Category fields to parse a draft saved footprint.");
      return;
    }

    try {
      setIsSubmitting(true);
      setSubmitError("");
      const fullFormValues = getValues();

      const cleanPrice = typeof fullFormValues.price === "string"
        ? (fullFormValues.price as string).replace(/,/g, "")
        : String(fullFormValues.price);

      // Post as a regular listing or draft state depending on how your backend parses data payload
      await createProperty({ ...fullFormValues, price: cleanPrice, status: "DRAFT" } as any);

      setSuccessMessage("Property saved carefully as draft ledger asset.");
      if (onClose) onClose();
      window.location.href = "/dashboard/listings";
    } catch (err: any) {
      setSubmitError(getErrorMessage(err, "Unable to register system draft fallback."));
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="w-full space-y-6">
      {/* Structural Progress Steps indicator */}
      <div className="flex items-center gap-4 bg-white border border-slate-200/60 p-4 rounded-2xl shadow-sm">
        <div className="flex-1 flex gap-2">
          {[1, 2, 3].map((step) => (
            <div
              key={step}
              className={`flex-1 h-2 rounded-full transition-all duration-300 ${step <= currentStep ? "bg-[#002045]" : "bg-slate-200"
                }`}
            />
          ))}
        </div>
        <span className="text-xs text-slate-500 font-semibold uppercase tracking-wider whitespace-nowrap">
          Step {currentStep} of 3
        </span>
      </div>

      {/* Messages */}
      {submitError && (
        <div className="p-4 bg-red-50 border border-red-100 rounded-xl flex items-start gap-3">
          <AlertCircle className="h-5 w-5 text-red-600 shrink-0 mt-0.5" />
          <p className="text-red-700 text-sm font-medium">{submitError}</p>
        </div>
      )}

      {successMessage && (
        <div className="p-4 bg-emerald-50 border border-emerald-100 rounded-xl flex items-start gap-3">
          <CheckCircle2 className="h-5 w-5 text-emerald-600 shrink-0 mt-0.5" />
          <p className="text-emerald-700 text-sm font-medium">{successMessage}</p>
        </div>
      )}

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">

        {/* STEP 1: Core Parameters */}
        {currentStep === 1 && (
          <div className="bg-white rounded-2xl border border-slate-200 p-6 space-y-5 shadow-sm">
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-2">
                Property Title <span className="text-red-500">*</span>
              </label>
              <input
                {...register("title")}
                type="text"
                placeholder="e.g. Modern Villa in Bole"
                className={`w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 focus:outline-none focus:border-[#002045] focus:ring-4 focus:ring-[#002045]/5 transition-all ${errors.title ? "border-red-300 bg-red-50/50" : ""
                  }`}
              />
              {errors.title && <p className="text-red-600 text-xs font-medium mt-1">{errors.title.message}</p>}
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-2">
                  Transaction Type <span className="text-red-500">*</span>
                </label>
                <div className="flex gap-1.5 p-1 bg-slate-100 rounded-xl border border-slate-200/50">
                  {["FOR_SALE", "FOR_RENT"].map((type) => (
                    <label key={type} className="flex-1 cursor-pointer">
                      <input {...register("listing_type")} type="radio" value={type} className="sr-only" />
                      <div className={`py-2 px-3 rounded-lg text-center text-xs font-bold transition-all ${watchListingType === type ? "bg-[#002045] text-white shadow-sm" : "text-slate-600 hover:bg-slate-200"
                        }`}>
                        {type === "FOR_SALE" ? "Sell" : "Rent"}
                      </div>
                    </label>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-2">
                  Property Type <span className="text-red-500">*</span>
                </label>
                <select
                  {...register("category")}
                  className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 bg-white focus:outline-none focus:border-[#002045] focus:ring-4 focus:ring-[#002045]/5 transition-all"
                >
                  <option value="RESIDENTIAL">Residential</option>
                  <option value="COMMERCIAL">Commercial</option>
                  <option value="INDUSTRIAL">Industrial</option>
                  <option value="AGRICULTURAL">Agricultural</option>
                </select>
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-2">
                Price (ETB) <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                placeholder="0.00"
                className={`w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 focus:outline-none focus:border-[#002045] focus:ring-4 focus:ring-[#002045]/5 transition-all ${errors.price ? "border-red-300 bg-red-50/50" : ""
                  }`}
                {...register("price", {
                  required: "Price is required",
                  onChange: (e) => {
                    const rawValue = e.target.value.replace(/[^0-9.]/g, "");
                    const parts = rawValue.split(".");
                    if (parts[0]) {
                      parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
                    }
                    e.target.value = parts.join(".");
                  }
                })}
              />
              {errors.price && (
                <p className="text-red-600 text-xs font-medium mt-1">
                  {errors.price.message}
                </p>
              )}
            </div>

            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-2">
                Address <span className="text-red-500">*</span>
              </label>
              <input
                {...register("address")}
                type="text"
                placeholder="Enter exact localized location details"
                className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 focus:outline-none focus:border-[#002045] focus:ring-4 focus:ring-[#002045]/5 transition-all"
              />
              {errors.address && <p className="text-red-600 text-xs font-medium mt-1">{errors.address.message}</p>}
            </div>

            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-700 mb-2">Description</label>
              <textarea
                {...register("description")}
                placeholder="Describe key amenities, neighborhood points..."
                rows={3}
                className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 focus:outline-none focus:border-[#002045] focus:ring-4 focus:ring-[#002045]/5 transition-all"
              />
            </div>
          </div>
        )}

        {/* STEP 2: Media Assembly & Pinpoint Coordinates */}
        {currentStep === 2 && (
          <div className="space-y-4">
            <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm">
              <h4 className="text-sm font-bold text-slate-800 uppercase tracking-wider mb-4">Location Coordinates</h4>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <input
                  {...register("latitude")}
                  placeholder="Latitude (e.g. 9.0234)"
                  className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 focus:outline-none focus:border-[#002045]"
                />
                <input
                  {...register("longitude")}
                  placeholder="Longitude (e.g. 38.7469)"
                  className="w-full px-4 py-2.5 text-sm rounded-xl border border-slate-200 focus:outline-none focus:border-[#002045]"
                />
              </div>
            </div>

            <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm space-y-4">
              <h4 className="text-sm font-bold text-slate-800 uppercase tracking-wider">Property Images</h4>
              <label className="block group">
                <div className="border-2 border-dashed border-slate-200 hover:border-[#002045] rounded-2xl p-6 flex flex-col items-center justify-center text-center cursor-pointer hover:bg-slate-50 transition-all">
                  <Cloud className="h-8 w-8 text-slate-400 group-hover:text-[#002045] mb-2 transition-colors" />
                  <p className="text-sm font-bold text-slate-800">Upload asset photographs</p>
                  <input type="file" multiple accept="image/*" onChange={(e) => handleImageSelect(e.target.files)} className="sr-only" />
                </div>
              </label>

              {uploadError && <p className="text-red-600 text-xs font-semibold">{uploadError}</p>}

              {previewUrls.length > 0 && (
                <div className="grid grid-cols-3 sm:grid-cols-5 gap-3 pt-2">
                  {previewUrls.map((url, index) => (
                    <div key={index} className="relative aspect-square rounded-xl overflow-hidden group border border-slate-100 bg-slate-50">
                      <img src={url} alt="Preview" className="w-full h-full object-cover" />
                      <button
                        title="Remove Image"
                        type="button"
                        onClick={() => handleRemoveImage(index)}
                        className="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity"
                      >
                        <Trash2 className="h-5 w-5 text-white" />
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}

        {/* STEP 3: Integrated Tier Selection & Ledger Review */}
        {currentStep === 3 && (
          <div className="space-y-6">
            {/* Integrated Tier Cards */}
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
              <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wider mb-4">Select Listing Tier</h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {PAYMENT_TIERS.map((tier) => (
                  <label
                    key={tier.id}
                    className={`flex items-start justify-between p-4 rounded-xl border-2 cursor-pointer transition ${watchTier === tier.id ? "border-[#002045] bg-slate-50/50" : "border-slate-200 hover:border-slate-300"
                      }`}
                  >
                    <div className="flex gap-3">
                      <input
                        type="radio"
                        value={tier.id}
                        {...register("tier")}
                        className="w-4 h-4 mt-0.5 text-[#002045] focus:ring-[#002045]"
                      />
                      <div>
                        <p className="font-bold text-sm text-slate-800">{tier.name}</p>
                        <p className="text-xs text-slate-500 mt-0.5">{tier.duration} • {tier.feature}</p>
                      </div>
                    </div>
                    <span className="font-bold text-sm text-slate-900">{tier.price} ETB</span>
                  </label>
                ))}
              </div>
            </div>

            <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm space-y-4">
              <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider border-b border-slate-100 pb-2">Review Summary</h4>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="text-xs text-slate-400 font-medium">Title</span>
                  <p className="font-semibold text-slate-800">{watch("title")}</p>
                </div>
                <div>
                  <span className="text-xs text-slate-400 font-medium">Total Price Due</span>
                  <p className="font-black text-[#002045] text-lg">{selectedTierData.price.toFixed(2)} ETB</p>
                </div>
              </div>

              <div className="p-4 bg-slate-50 border border-slate-200 rounded-xl flex gap-3 text-xs text-slate-600">
                <Shield className="w-4 h-4 text-[#002045] flex-shrink-0 mt-0.5" />
                <p>Secure authorization via Chapa. Accepts Telebirr, CBE Birr, and international cards.</p>
              </div>
            </div>
          </div>
        )}

        {/* Action Controls Tray */}
        <div className="flex items-center justify-between pt-4 border-t border-slate-200/60">
          <Button
            type="button"
            onClick={handlePrevStep}
            disabled={currentStep === 1 || isSubmitting}
            variant="outline"
            className="rounded-xl text-xs font-bold"
          >
            Back
          </Button>

          <div className="flex items-center gap-2">
            {onClose && (
              <Button
                type="button"
                onClick={onClose}
                disabled={isSubmitting}
                variant="ghost"
                className="rounded-xl text-xs text-slate-400 font-bold"
              >
                Cancel
              </Button>
            )}

            {currentStep < 3 ? (
              <Button
                type="button"
                onClick={handleNextStep}
                disabled={isSubmitting}
                className="rounded-xl px-6 bg-[#002045] hover:bg-[#1a365d] text-white text-xs font-bold"
              >
                Continue
              </Button>
            ) : (
              <>
                <Button
                  type="button"
                  onClick={handleSaveDraftManual}
                  disabled={isSubmitting}
                  variant="outline"
                  className="rounded-xl text-xs font-bold"
                >
                  Save as draft
                </Button>

                <Button
                  type="submit"
                  disabled={isSubmitting}
                  className="rounded-xl px-6 gap-2 bg-[#002045] hover:bg-[#1a365d] text-white text-xs font-bold shadow-md"
                >
                  {isSubmitting && <Loader2 className="h-3.5 w-3.5 animate-spin" />}
                  {isSubmitting ? "Processing..." : `Pay ${selectedTierData.price} ETB →`}
                </Button>
              </>
            )}
          </div>
        </div>
      </form>
    </div>
  );
}